/*
 *  ROBIT - El robot simpático e inteligente
 *  Copyright (C) 2010  Kenny Meyer <knny.myer@gmail.com>
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 *  --
 *
 *  Este programa es software libre: usted puede redistribuirlo y/o modificarlo
 *  conforme a los términos de la Licencia Pública General de GNU publicada por
 *  la Fundación para el Software Libre, ya sea la versión 3 de esta Licencia o (a
 *  su elección) cualquier versión posterior.
 *
 *  Este programa se distribuye con el deseo de que le resulte útil, pero SIN
 *  GARANTÍAS DE NINGÚN TIPO; ni siquiera con las garantías implícitas de
 *  COMERCIABILIDAD o APTITUD PARA UN PROPÓSITO DETERMINADO.  Para más información,
 *  consulte la Licencia Pública General de GNU.
 *
 *  Junto con este programa, se debería incluir una copia de la Licencia Pública General de GNU.
 *  De no ser así, ingrese en <http://www.gnu.org/licenses/>.
 */
package robit;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DialogoCreditos.java
 *
 * Created on 26/09/2010, 06:43:12 PM
 */

/**
 *
 * @author kenny
 */

import lib.Picture;

public class DialogoCreditos extends javax.swing.JDialog {

    /** Creates new form DialogoCreditos */
    public DialogoCreditos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    public void init() {
        Picture picture = new Picture("data/creditos_small.jpg");
        creditosPanel.add("Creditos", picture.getJLabel());
        pack();
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        acercaDe = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        creditosPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane1.setBorder(null);

        jEditorPane1.setContentType("text/html");
        jEditorPane1.setEditable(false);
        jEditorPane1.setText("<html>\n  <head>\n\n  </head>\n  <body>\n    <p style=\"margin-top: 0\">\n      <b>ROBIT es un proyecto elaborado por el Segundo Curso del Segundo Año del Colegio Nacional E.M.D. \"Dr. Raúl Peña\" Caacupé - Paraguay.</b><br /><br />\n\n      <b>Página web/Blog:</b><a href=\"http://robitweb.blogspot.com\">robitweb.blogspot.com</a><br />\n      <b>Versión:</b>1.0<br /></br>\n      <b>Reportar parches/bugs:</b> Si encuentras algun error, abre un nuevo ticket en <a href=\"http://github.com/km0r3/robit/issues\">GitHub</a><br />\n      Si queres contribuir nuevas ideas en forma de código, imagenes, audio, etc. podes obtener el código de GitHub, y así crear, con Git, el parche.<br /><br />\n\n      <b>Consultas:</b> <a href=\"mailto:knny.myer@gmail.com\">por mail.<a>\n    </p>\n  </body>\n</html>\n");
        jEditorPane1.setDoubleBuffered(true);
        jScrollPane1.setViewportView(jEditorPane1);

        javax.swing.GroupLayout acercaDeLayout = new javax.swing.GroupLayout(acercaDe);
        acercaDe.setLayout(acercaDeLayout);
        acercaDeLayout.setHorizontalGroup(
            acercaDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(acercaDeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addContainerGap())
        );
        acercaDeLayout.setVerticalGroup(
            acercaDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(acercaDeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Acerca de", acercaDe);

        creditosPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        creditosPanel.setLayout(new java.awt.CardLayout());
        jTabbedPane1.addTab("Créditos", creditosPanel);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogoCreditos dialog = new DialogoCreditos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel acercaDe;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel creditosPanel;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

}
