package robit;

/*
 * MenuPrincipal.java
 *
 * Created on 12/09/2010, 08:21:23 AM
 *
 * Esta clase muestra el Menú principal.  Es recomendable, sino necesario, que
 * el usuario primero hace llama a este objeto.
 *
 */
import lib.Picture;
import lib.Sonido;

import javax.swing.JLabel;
import javax.swing.JPanel;


public class MenuPrincipal extends javax.swing.JFrame {
    String archivoRobitFeliz    = "data/robit/feliz.png";
    String archivoRobitTriste   = "data/robit/triste.png";
    String archivoRobitBitFlip  = "data/robit/bitFlip.png";
    String archivoRobitSignMix  = "data/robit/signMix.png";

    JPanel subPanel = new JPanel();

    JLabel robitBienvenidos  = new Picture(archivoRobitFeliz)   .getJLabel();
    JLabel robitTristeLabel  = new Picture(archivoRobitTriste)  .getJLabel();
    JLabel robitBitFlipLabel = new Picture(archivoRobitBitFlip) .getJLabel();
    JLabel robitSignMixLabel = new Picture(archivoRobitSignMix) .getJLabel();

    // Instancias de nuestros juegos.
    juegos.bitFlip.GamePanel bitFlip = new juegos.bitFlip.GamePanel();
    juegos.signMix.SignMixPanel signMix = new juegos.signMix.SignMixPanel();

    /**
     * El inicializador (...y el TERMINATOR?)
     */
    public MenuPrincipal() {
        initComponents();
        init();
    }

    /**
     * Arreglar los elementos en la ventana.
     */
    public void init() {
        this.subPanel.add(this.robitBienvenidos);
        this.subPanel.add(this.robitTristeLabel);
        this.subPanel.add(this.robitBitFlipLabel);
        this.subPanel.add(this.robitSignMixLabel);

        this.robitTristeLabel.setVisible(false);
        this.robitBitFlipLabel.setVisible(false);
        this.robitSignMixLabel.setVisible(false);

        panelPrincipal.add(this.subPanel);
        panelPrincipal.add(bitFlip);
        // Añadir bitFlip al panel
        bitFlip.setVisible(false);
        // Añadir signMix al panel
        panelPrincipal.add(signMix);
        signMix.setVisible(false);
        pack();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panelPrincipal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnBitFlip = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnCreditos = new javax.swing.JButton();
        btnSignMix = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ROBIT");

        panelPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelPrincipal.setMaximumSize(new java.awt.Dimension(0, 0));
        panelPrincipal.setLayout(new java.awt.CardLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnBitFlip.setText("BitFlip");
        btnBitFlip.setMaximumSize(new java.awt.Dimension(100, 100));
        btnBitFlip.setMinimumSize(new java.awt.Dimension(100, 100));
        btnBitFlip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBitFlipMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBitFlipMouseEntered(evt);
            }
        });
        btnBitFlip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBitFlipActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
        });
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnCreditos.setText("Créditos");
        btnCreditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCreditosMouseEntered(evt);
            }
        });
        btnCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditosActionPerformed(evt);
            }
        });

        btnSignMix.setText("SignMix");
        btnSignMix.setMaximumSize(new java.awt.Dimension(100, 100));
        btnSignMix.setMinimumSize(new java.awt.Dimension(100, 100));
        btnSignMix.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSignMixMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSignMixMouseEntered(evt);
            }
        });
        btnSignMix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignMixActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(btnBitFlip, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(btnCreditos, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(btnSignMix, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(btnBitFlip, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSignMix, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(btnCreditos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBitFlipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBitFlipActionPerformed
        // Llamar al cuadro del juego BitFlip.
        // Reemplazar el contenido del panel principal.
        this.subPanel.setVisible(false);
        this.bitFlip.setVisible(true);
        pack();
    }//GEN-LAST:event_btnBitFlipActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // Salir de ROBIT :'-(
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditosActionPerformed
        DialogoCreditos creditos = new DialogoCreditos(this, false);
        creditos.setVisible(true);
    }//GEN-LAST:event_btnCreditosActionPerformed

    private void btnBitFlipMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBitFlipMouseEntered
        this.robitBienvenidos.setVisible(false);
        this.robitBitFlipLabel.setVisible(true);
        this.validate();
        Sonido.reproducirSonidoHover();
    }//GEN-LAST:event_btnBitFlipMouseEntered

    private void btnBitFlipMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBitFlipMouseExited
        this.robitBitFlipLabel.setVisible(false);
        this.robitBienvenidos.setVisible(true);
        this.validate();
    }//GEN-LAST:event_btnBitFlipMouseExited

    private void btnSignMixMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignMixMouseExited
        this.robitSignMixLabel.setVisible(false);
        this.robitBienvenidos.setVisible(true);
        this.validate();
    }//GEN-LAST:event_btnSignMixMouseExited

    private void btnSignMixMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignMixMouseEntered
        this.robitBienvenidos.setVisible(false);
        this.robitSignMixLabel.setVisible(true);
        this.validate();
        Sonido.reproducirSonidoHover();
    }//GEN-LAST:event_btnSignMixMouseEntered

    private void btnSignMixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignMixActionPerformed
        // Llamar al panel del juego SignMix.
        // Reemplazar el contenido del panel principal.
        this.subPanel.setVisible(false);
        this.signMix.setVisible(true);
        pack();
    }//GEN-LAST:event_btnSignMixActionPerformed

    private void btnCreditosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreditosMouseEntered
        Sonido.reproducirSonidoHover();
    }//GEN-LAST:event_btnCreditosMouseEntered

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        this.robitBienvenidos.setVisible(false);
        this.robitTristeLabel.setVisible(true);
        Sonido.reproducirSonidoHover();
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        this.robitTristeLabel.setVisible(false);
        this.robitBienvenidos.setVisible(true);
        Sonido.reproducirSonidoHover();
    }//GEN-LAST:event_btnSalirMouseExited

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBitFlip;
    private javax.swing.JButton btnCreditos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSignMix;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables

}