/*
 * GameApplet.java
 *
 * Created on Sep 5, 2010, 7:24:05 AM
 */

package bitFlip;
/**
 *
 * @author kenny
 */

public class GameApplet extends javax.swing.JApplet {

    private Generator generator;
    /** Initializes the applet GameApplet */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        this.generator = new Generator();
        setSize(new java.awt.Dimension(500, 600));
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        btnSi = new java.awt.Button();
        btnNo = new java.awt.Button();
        panel2 = new java.awt.Panel();
        btnReset = new java.awt.Button();
        canvas1 = new GameCanvas();

        setStub(null);
        setLayout(new java.awt.BorderLayout());

        btnSi.setLabel("Sí");
        btnSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiActionPerformed(evt);
            }
        });
        panel1.add(btnSi);

        btnNo.setLabel("No");
        btnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoActionPerformed(evt);
            }
        });
        panel1.add(btnNo);

        panel2.setLayout(new javax.swing.BoxLayout(panel2, javax.swing.BoxLayout.LINE_AXIS));

        btnReset.setLabel("Reset");
        panel2.add(btnReset);

        panel1.add(panel2);

        add(panel1, java.awt.BorderLayout.SOUTH);
        add(canvas1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiActionPerformed
        this.generator.yes();
    }//GEN-LAST:event_btnSiActionPerformed

    private void btnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoActionPerformed
        this.generator.no();
    }//GEN-LAST:event_btnNoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnNo;
    private java.awt.Button btnReset;
    private java.awt.Button btnSi;
    private java.awt.Canvas canvas1;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    // End of variables declaration//GEN-END:variables

}
