package signMix;

import java.util.ArrayList;

/**
 *
 * @author Kenny Meyer <knny.myer@gmail.com>
 * @author Jorge Gimenez <jrg.gmnz@hotmail.com>
 *
 * TODO: El temporizador
 */
public class SignMixPanel extends javax.swing.JPanel {

    private Generator generador = new Generator();
    private ArrayList<String> numeros = new ArrayList<String>();
    /** El nivel del juego
     *
     * De acuerdo al nivel se mostrarán más etiquetas y entradas de texto.
     *
     */
    private int nivel = 1;

    /** Creates new form SignMixFrame */
    public SignMixPanel() {
        initComponents();
        // Porque empezamos en el nivel 1 al principio ocultar los otros controles
        etiTercerNumero.setVisible(false);
        etiCuartoNumero.setVisible(false);
        txtSigno2      .setVisible(false);
        txtSigno3      .setVisible(false);
        reset();
    }

    /**
     * Subir de nivel.
     * 
     * Incrementar el nivel, y desplegar los nuevos controles de acuerdo al nivel.
     */
    public void subirNivel() {
        incrementarNivel();
        if ( this.nivel == 2 ) {
            this.numeros = generador.generarProblema(2);

            etiTercerNumero.setVisible(true);
            txtSigno2      .setVisible(true);

            etiPrimer      .setText(this.numeros.get(0));
            txtSigno1      .setText("");
            etiSegundo     .setText(this.numeros.get(2));
            etiTercerNumero.setText(this.numeros.get(4));
            etiResultado   .setText(this.numeros.get(5));

            etiMensaje          .setText("correcto!!! pasaste al siguiente nivel");
         } else if( this.nivel == 3 ) {
             this.numeros = generador.generarProblema(3);

             etiCuartoNumero.setVisible(true);
             txtSigno3      .setVisible(true);

             etiPrimer      .setText(this.numeros.get(0));
             txtSigno1      .setText("");
             txtSigno2      .setText("");
             etiSegundo     .setText(this.numeros.get(2));
             etiTercerNumero.setText(this.numeros.get(4));
             etiCuartoNumero.setText(this.numeros.get(6));
             etiResultado   .setText(this.numeros.get(7));

             etiMensaje     .setText("correcto!!! pasaste al siguiente nivel");
         } else {
             etiMensaje .setText("Ganaste!!!!felicidades!!");
             jPanel1    .remove(jPanel4);
             Felicidades feliz = new Felicidades();
             jPanel1    .add(feliz);
         }
    }

    private void reset() {
        // Generar nuevos numeros
        this.numeros = generador.generarProblema(1);
        // Reemplazar los controles de la ventana.
        etiPrimer.setText(this.numeros.get(0));
        txtSigno1.setText("");
        etiSegundo.setText(this.numeros.get(2));
        etiResultado.setText(this.numeros.get(3));
        nivel=1;

    }

    public void incrementarNivel() {
        this.nivel++;
    }

    public void resetearNivel() {
        this.nivel = 1;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        etiMensaje = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        etiPrimer = new javax.swing.JLabel();
        txtSigno1 = new javax.swing.JTextField();
        etiSegundo = new javax.swing.JLabel();
        txtSigno2 = new javax.swing.JTextField();
        etiTercerNumero = new javax.swing.JLabel();
        txtSigno3 = new javax.swing.JTextField();
        etiCuartoNumero = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        etiResultado = new javax.swing.JLabel();

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        etiMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiMensaje.setText("El mensaje a desplegar...");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setLayout(new java.awt.GridLayout());

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        jPanel3.add(btnOk);

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.GridLayout());

        jPanel4.setLayout(new java.awt.GridBagLayout());

        etiPrimer.setText("PrimerNumero");
        jPanel4.add(etiPrimer, new java.awt.GridBagConstraints());

        txtSigno1.setColumns(1);
        jPanel4.add(txtSigno1, new java.awt.GridBagConstraints());

        etiSegundo.setText("SegundoNumero");
        jPanel4.add(etiSegundo, new java.awt.GridBagConstraints());

        txtSigno2.setColumns(1);
        jPanel4.add(txtSigno2, new java.awt.GridBagConstraints());

        etiTercerNumero.setText("TercerNumero");
        jPanel4.add(etiTercerNumero, new java.awt.GridBagConstraints());

        txtSigno3.setColumns(1);
        jPanel4.add(txtSigno3, new java.awt.GridBagConstraints());

        etiCuartoNumero.setText("CuartoNumero");
        jPanel4.add(etiCuartoNumero, new java.awt.GridBagConstraints());

        jLabel3.setText(" = ");
        jPanel4.add(jLabel3, new java.awt.GridBagConstraints());

        etiResultado.setText("Resultado");
        jPanel4.add(etiResultado, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                        .addGap(153, 153, 153)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        /*
         * Cuando el jugador aprieta el botón OK, verificar que el resultado
         * sea correcto.
         */

        // El patrón
        String masOMenos = "^(\\+|\\-)"; // O "+" o "-"

        if ( nivel == 1 ) {
            if ( txtSigno1.getText().matches(masOMenos)) {
                // Comparar el primer signo en la lista.
                if (txtSigno1.getText().startsWith(
                        this.generador.obtenerSigno(
                            this.numeros.get(1)
                            )
                        )
                    ) {
                    // El signo está correcto ...
                    etiMensaje.setText("Correcto! Sos un master!");
                    // y subir de nivel...
                    subirNivel();
                } else {
                    etiMensaje.setText("No está correcto. Intentá de nuevo.");
                }
            } else {
                etiMensaje.setText("Ingrese el signo + ó - !");
            }
        } else if ( nivel==2 ) {
            if ( txtSigno1.getText().matches(masOMenos) &&
                 txtSigno2.getText().matches(masOMenos)) {
                // Comparar el primer y segundo signo en la lista.
                if (( txtSigno1.getText().startsWith(
                        this.generador.obtenerSigno(
                            this.numeros.get(1))) &&
                    ( txtSigno2.getText().startsWith(
                        this.generador.obtenerSigno(
                            this.numeros.get(3))
                            )
                        )
                    )) {
                    // El signo está correcto ...
                    etiMensaje.setText("Correcto! Sos un master!");
                    // y subir de nivel...
                    subirNivel();

                } else {
                    etiMensaje.setText("No está correcto. Intentá de nuevo.");
                }
            } else {
                etiMensaje.setText("Ingrese el signo + ó - !");
            }
        } else if ( nivel== 3 ) {
            if ( txtSigno1.getText().matches(masOMenos) &&
                 txtSigno2.getText().matches(masOMenos) &&
                 txtSigno3.getText().matches(masOMenos)) {
                // Comparar el primer, segundo y tercer signo en la lista.
                if (( txtSigno1.getText().startsWith(
                        this.generador.obtenerSigno(
                            this.numeros.get(1)))) &&
                    ( txtSigno2.getText().startsWith(
                        this.generador.obtenerSigno(
                            this.numeros.get(3)))) &&
                    ( txtSigno3.getText().startsWith(
                        this.generador.obtenerSigno(
                            this.numeros.get(5))))
                    ) {
                    // Los signos se ha puestos correctamente
                    etiMensaje.setText("Correcto! Sos un master!");
                    // y subir de nivel...
                    subirNivel();

                } else {
                    etiMensaje.setText("No está correcto. Intentá de nuevo.");
                }
            } else {
                etiMensaje.setText("Ingrese el signo + ó - !");
            }
        }
}//GEN-LAST:event_btnOkActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        reset();
}//GEN-LAST:event_btnResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel etiCuartoNumero;
    private javax.swing.JLabel etiMensaje;
    private javax.swing.JLabel etiPrimer;
    private javax.swing.JLabel etiResultado;
    private javax.swing.JLabel etiSegundo;
    private javax.swing.JLabel etiTercerNumero;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtSigno1;
    private javax.swing.JTextField txtSigno2;
    private javax.swing.JTextField txtSigno3;
    // End of variables declaration//GEN-END:variables

}
