/*
 * SignMix.java
 *
 * Created on Sep 5, 2010, 9:49:44 AM
 */

package signMix;

import java.util.ArrayList;


/**
 *
 * @author Kenny Meyer
 * @author Jorge Gimenez
 */
public class SignMix extends javax.swing.JApplet {

    private Generator generador = new Generator();
    private ArrayList<String> numeros = generador.generador();

    /** Initializes the applet SignMix */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        reset();
    }


    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        etiPrimer = new java.awt.Label();
        txtSigno1 = new java.awt.TextField();
        etiSegundo = new java.awt.Label();
        label3 = new java.awt.Label();
        etiResultado = new java.awt.Label();
        etiMensaje = new java.awt.Label();
        panel2 = new java.awt.Panel();
        btnOK = new java.awt.Button();
        btnReset = new java.awt.Button();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        etiPrimer.setAlignment(java.awt.Label.CENTER);
        etiPrimer.setName("etiPrimer"); // NOI18N
        etiPrimer.setText("PrimerNumero");
        panel1.add(etiPrimer);

        txtSigno1.setName("txtSigno1"); // NOI18N
        txtSigno1.setText("   ");
        panel1.add(txtSigno1);

        etiSegundo.setAlignment(java.awt.Label.CENTER);
        etiSegundo.setName("etiSegundo"); // NOI18N
        etiSegundo.setText("SegundoNumero");
        panel1.add(etiSegundo);

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setText("=");
        panel1.add(label3);

        etiResultado.setAlignment(java.awt.Label.CENTER);
        etiResultado.setName("etiResultado"); // NOI18N
        etiResultado.setText("Resultado");
        panel1.add(etiResultado);

        etiMensaje.setAlignment(java.awt.Label.CENTER);
        etiMensaje.setText("nada");
        panel1.add(etiMensaje);

        add(panel1, java.awt.BorderLayout.CENTER);

        panel2.setLayout(new java.awt.GridLayout());

        btnOK.setLabel("OK");
        btnOK.setName("OK"); // NOI18N
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        panel2.add(btnOK);

        btnReset.setLabel("Reset");
        btnReset.setName("btnReset"); // NOI18N
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        panel2.add(btnReset);

        add(panel2, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * TODO:
     *  - Crear los niveles
     *  - Obtener el resultado de la lista(ultimo elemento de la lista)
     */
    private void reset() {
        // Generar nuevos numeros
        this.numeros = generador.generador();
        // Reemplazar los controles de la ventana.
        etiPrimer.setText(this.numeros.get(0));
        etiSegundo.setText(this.numeros.get(2));
        etiResultado.setText(this.numeros.get(3));
    }

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        /* Tenemos que controlar que txtSigno no está vacío. -> Mostar un
         * mensaje si no se completó.
         */
        System.out.println(txtSigno1.getText());
        if (txtSigno1.getText().startsWith("+") ||
            txtSigno1.getText().startsWith("-")) {
            // Comparar el signo en la lista.
            if (txtSigno1.getText().startsWith(this.numeros.get(1))) {
                // El signo está correcto
                etiMensaje.setText("Correcto! Sos un master!");
                reset();
            } else {
                etiMensaje.setText("No está correcto. Intentá de nuevo.");
            }
        } else {
            etiMensaje.setText("Ingrese el signo + ó - !");
        }
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        reset();
    }//GEN-LAST:event_btnResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnOK;
    private java.awt.Button btnReset;
    private java.awt.Label etiMensaje;
    private java.awt.Label etiPrimer;
    private java.awt.Label etiResultado;
    private java.awt.Label etiSegundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label3;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.TextField txtSigno1;
    // End of variables declaration//GEN-END:variables

}