/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdivinaNumeroApplet.java
 *
 * Created on Sep 5, 2010, 8:26:53 AM
 */

package adivinaNumero;

/**
 *
 * @author kenny
 */
public class AdivinaNumeroApplet extends java.applet.Applet {

    private int paso = 0;
    private int num_aleatorio = 0;
    /** Initializes the applet AdivinaNumeroApplet */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        btnListo = new java.awt.Button();
        btnReset = new java.awt.Button();
        panel2 = new java.awt.Panel();
        txtTitulo = new javax.swing.JLabel();
        panel3 = new java.awt.Panel();
        txtResultado = new java.awt.TextField();

        setLayout(new java.awt.BorderLayout());

        btnListo.setLabel("Listo?");
        btnListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListoActionPerformed(evt);
            }
        });
        panel1.add(btnListo);

        btnReset.setLabel("Reset");
        btnReset.setVisible(false);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        panel1.add(btnReset);

        add(panel1, java.awt.BorderLayout.SOUTH);

        txtTitulo.setText("Piensa en un numero");
        panel2.add(txtTitulo);

        add(panel2, java.awt.BorderLayout.NORTH);

        txtResultado.setText("textField1");
        txtResultado.setVisible(false);
        panel3.add(txtResultado);

        add(panel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListoActionPerformed
        if (this.paso == 0) {
            java.awt.Dimension dimensionLocal = new java.awt.Dimension();
            txtTitulo.setText("Ahora multiplique el numero por 2");
            txtTitulo.setSize(
                    dimensionLocal.width,
                    dimensionLocal.height);
            btnReset.setVisible(false);
            this.paso++;
        } else if (this.paso == 1) {
            this.num_aleatorio = (int)((Math.random()* 10) + 1);
            java.awt.Dimension dimensionLocal = new java.awt.Dimension();
            txtTitulo.setText("Sumar " + this.num_aleatorio + " al numero.");
            txtTitulo.setSize(
                    dimensionLocal.width,
                    dimensionLocal.height);
            this.paso++;
        } else if (this.paso == 2) {
            java.awt.Dimension dimensionLocal = new java.awt.Dimension();
            txtTitulo.setText("Ahora divide el numero por 2.");
            txtTitulo.setSize(
                    dimensionLocal.width,
                    dimensionLocal.height);
            repaint();
            this.paso++;
        } else if (this.paso == 3) {
            java.awt.Dimension dimensionLocal = new java.awt.Dimension();
            txtTitulo.setText("Resta el numero que pensaste previamente.");
            txtTitulo.setSize(
                    dimensionLocal.width,
                    dimensionLocal.height);
            this.paso++;
        } else if (this.paso == 4) {
            System.out.println(num_aleatorio);
            txtResultado.setText("El resultado es: " + this.num_aleatorio / 2);
            txtResultado.setVisible(true);
            btnReset.setVisible(true);
        }
    }//GEN-LAST:event_btnListoActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        this.paso = 0; // Re-inicar
    }//GEN-LAST:event_btnResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnListo;
    private java.awt.Button btnReset;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.TextField txtResultado;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration//GEN-END:variables

}
